url: "https://scuttlecat.github.io"
baseurl: "/scuttlefaq"

title: "scuttlefaq"
description: "stupid fucking questions"

embed_color: "#5865F2"

collections:
  faqs:
    output: true
    permalink: /faq/:name/

faq_categories:
  - "General"
  - "Seasons & Ranked"
  - "Skins"
  - "Shops & Currency"

defaults:
  - scope:
      path: ""
      type: faqs
    values:
      layout: faq
